apiVersion: v1
kind: Service
metadata:
  name: safety-vnf-service
spec:
  selector:
    app: safety-vnf
  ports:
    - name: web-ui
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 30053
  type: NodePort
